package com.akhbar24.tests;
import io.appium.java_client.AppiumBy;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.time.Duration;
import java.util.List;


import com.akhbar24.utils.BaseTest;

public class ContactUsTest extends BaseTest {

    private WebElement waitForElement(By locator) {
        return new WebDriverWait(driver, Duration.ofSeconds(60))
                .until(ExpectedConditions.presenceOfElementLocated(locator));
    }

     private void scrollToText(String visibleText) {
        driver.findElement(AppiumBy.androidUIAutomator(
                "new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView("
                        + "new UiSelector().descriptionContains(\"" + visibleText + "\"))"));
    }

    private void verifyUserIsLoggedIn() {
        boolean isHomeVisible = driver.getPageSource().contains("الرئيسية");
        Assert.assertTrue(isHomeVisible, "❌ لم يتم عرض صفحة الرئيسية بعد تسجيل الدخول.");

        waitForElement(AppiumBy.accessibilityId("القائمة")).click();
        String userStatus = waitForElement(By.xpath("//android.view.View[@content-desc]"))
                .getAttribute("content-desc");
        System.out.println("👤 الحالة الحالية للمستخدم: " + userStatus);
        Assert.assertFalse(userStatus.contains("زائر"), "❌ ما زال المستخدم زائرًا، يبدو أن تسجيل الدخول لم ينجح.");
    }

    @Test
    public void testContactUsFormSubmission() {

        try {
            System.out.println("🚀 بدء تسجيل الدخول...");

            // تسجيل الدخول
            waitForElement(AppiumBy.accessibilityId("القائمة")).click();
            waitForElement(By.xpath("//android.view.View[@content-desc='تسجيل دخول']")).click();

            List<WebElement> inputs = driver.findElements(By.className("android.widget.EditText"));
            Actions actions = new Actions(driver);
            actions.click(inputs.get(0)).perform();
            inputs.get(0).sendKeys("asilyacoub1@gmail.com");

            actions.click(inputs.get(1)).perform();
            inputs.get(1).sendKeys("123456789");

            waitForElement(AppiumBy.accessibilityId("تسجيل الدخول")).click();
            Thread.sleep(4000);
            verifyUserIsLoggedIn();

            // افتح القائمة
            waitForElement(AppiumBy.accessibilityId("القائمة")).click();

            // Scroll إلى "اتصل بنا"
            scrollToText("اتصل بنا");

            // اضغط على "اتصل بنا"
            waitForElement(AppiumBy.accessibilityId("اتصل بنا")).click();

            // ⌨️ الاسم
            WebElement nameField = waitForElement(By.xpath("//android.widget.EditText[1]"));
            nameField.click();
            nameField.sendKeys("Asil");

            // ⌨️ البريد الإلكتروني
            WebElement emailField = waitForElement(By.xpath("//android.widget.EditText[2]"));
            emailField.click();
            emailField.sendKeys("asilyacoub1@gmail.com");

            // ⌨️ نص الرسالة
            WebElement messageField = waitForElement(By.xpath("//android.widget.EditText[3]"));
            messageField.click();
            messageField.sendKeys("This is a test message generated by an automation script");
            // اضغط على "إرسال"
            waitForElement(AppiumBy.accessibilityId("إرسال")).click();

            // انتظر رسالة نجاح (بفرض تظهر عنصر content-desc فيه "تم")
            By successMsgLocator = By.xpath("//android.view.View[contains(@content-desc, 'تم')]");
            WebElement successMsg = new WebDriverWait(driver, Duration.ofSeconds(5))
                    .until(driver -> driver.findElements(successMsgLocator).size() > 0
                            ? driver.findElement(successMsgLocator)
                            : null);

            Assert.assertNotNull(successMsg, "❌ لم تظهر رسالة تأكيد الإرسال.");
            System.out.println("✅ تم إرسال الرسالة بنجاح.");

        } catch (Exception e) {
            takeScreenshot("contact_us_failure");
            Assert.fail("❌ فشل في إرسال نموذج الاتصال: " + e.getMessage());
        }
    }
}
